side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^result$', views.result, name="result"),
    url(r'^show/$', views.show, name="show"),
    url(r'^add/$', views.add, name="add"),
    url(r'^create_book/$', views.create_book, name="create_book"),
]

side-project/DjangoEnv/Python_Fundamentals/review/apps/logreg/urls.py
from django.conf.urls import url
from .models import User
from . import views
urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^register$',views.register, name="register"),
    url(r'^login$',views.login, name="login"),
    url(r'^main$',views.main, name="main"),
    url(r'^logout$',views.logout, name="logout")
]

side-project/DjangoEnv/Python_Fundamentals/review/review/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.logreg.urls', namespace='logreg')),
    url(r'^Book/', include('apps.Book.urls', namespace='Book'))
]

side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/models.py
from __future__ import unicode_literals
from ..logreg.models import User
from django.db import models

# Create your models here.
class Boo_review_Manager(models.Manager):
    def input_check(self, postdata):
        errors = []
        if not len(postdata['title']):
            errors.append('title must enter')
        if not len(postdata['author']):
            errors.append('author must enter')
        if not len(postdata['description']):
            errors.append('description must enter')

        response = {}
        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status'] = True
            self.create(title=postdata['title'],author=postdata['author'],description=postdata['description'], rating=postdata['rating'])
        return response

        def review_check(self, postdata):
            errors =[]
            if not len(postdata['review']):
                errors.append('review must enter')

            response = {}
            if errors:
                response['status'] = False
                response['errors'] = errors
            else:
                response['status'] = True
                self.create(review=postdata['review'])
            return response
            
class Book_review(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    rating = models.IntegerField()
    user = models.ManyToManyField(User, related_name="user")
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    objects = Boo_review_Manager()

class review(models.Model):
    review = models.TextField()
    create_at = models.DateTimeField()

side-project/DjangoEnv/Python_Fundamentals/review/apps/logreg/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-z0-9.+_-]+@[a-zA-z0-9._-]+\.[a-zA-z]+$')
# Create your models here.
class UserManager(models.Manager):
    def add_user(self, postData):
        print postData

        errors = []

        if not postData['first_name']:
            errors.append('First name field is required')
        if len(postData['first_name']) < 2:
            errors.append('First name must be at least 2 characters long.')
        if not postData['last_name']:
            errors.append('Last name field is required')
        if len(postData['last_name']) < 2:
            errors.append('Last name must be at least 2 characters long.')
        if not postData['email']:
            errors.append('Email field is required')
        if not EMAIL_REGEX.match(postData['email']):
            errors.append('Enter a valid email')
        if not postData['password']:
            errors.append('Password is required')
        if not postData['password'] == postData['confirm_password']:
            errors.append('Password must match')

        user = self.filter(email=postData['email'])
        if user:
            errors.append('Email already exists')

        response = {}

        if errors:
            response['status'] = False
            response['errors'] = errors

        else:
            password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            new_user = self.create(first_name = postData['first_name'],
                        last_name = postData['last_name'],
                        email = postData['email'],
                        password = password
            )
            response['status'] = True
            response['new_user'] = new_user

        return response

    def check_user(self, postData):
        user = self.filter(email=postData['email'])
        errors = []
        response = {}
        if user:
           #validate User login information
           #bcrypt.checkpw(postData['password'].encode(), bcrypt.gensalt())
           if bcrypt.hashpw(postData['password'].encode(), user[0].password.encode()) == user[0].password.encode():
               print("It Matched")
               response['status'] = True
               response['login_user'] = user[0]
           else:
               print("It Does Not Match")
               errors.append('Invalide email/password combinnation')
               response['status'] = False
               response['errors'] = errors
        else:
           #email does not exists in database
           errors.append('Email does not exist.')
           response['status'] = False
           response['errors'] = errors

        return response


class User(models.Model):
     first_name = models.CharField(max_length=55)
     last_name = models.CharField(max_length=55)
     email = models.EmailField()
     password = models.CharField(max_length=55)
     confirm_password = models.CharField(max_length=55)
     objects = UserManager()

side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/views.py
from django.shortcuts import render, redirect
from .models import Book_review
from ..logreg.models import User
from django.core.urlresolvers import reverse
from django.contrib import messages
# Create your views here.
def index(request):
    contex={
      "Book":Book_review.objects.all()
    }
    return render(request,'Book/index.html', contex)

def result(request):
    contex={
      "Book":Book_review.objects.all()
    }
    return render(request,'Book/result.html', contex)

def show(request):
    contex={
      "Book":Book_review.objects.all()
    }
    return render(request,'Book/show.html', contex)

def add(request):
    contex={
      "Book":Book_review.objects.all(),
      "User":User.objects.all()
    }
    return render(request,'Book/add.html', contex)

def create_book(request):
    response = Book_review.objects.input_check(request.POST)
    if not response['status']:
        for error in response['errors']:
            messages.error(request, error)
    return redirect(reverse('Book:result'))

def delete(request, id):
    Book.review.get(id=id).delete()
    return redirect(reverse('Book:result'))

side-project/DjangoEnv/Python_Fundamentals/review/apps/logreg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.core.urlresolvers import reverse
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, 'logreg/index.html')

def register(request):
    response = User.objects.add_user(request.POST)
    if response['status']:
        # successful add a new user in here
       request.session['user_id'] = response['new_user'].id
       request.session['user_first_name'] = response['new_user'].first_name
       request.session['user_last_name'] = response['new_user'].last_name
       return redirect('logreg:main')
    else:
       for error in response['errors']:
           messages.error(request, error)
    return redirect('logreg:index')

def login(request):
    response = User.objects.check_user(request.POST)
    if response['status']:
        # successful login user in here
       request.session['user_id'] = response['login_user'].id
       request.session['user_first_name'] = response['login_user'].first_name
       request.session['user_last_name'] = response['login_user'].last_name
       return redirect('logreg:main')
    else:
       #falid to validate
       for error in response['errors']:
           messages.error(request, error)
       return redirect('logreg:index')

def main(request):
    if "user_id" not in request.session:
        messages.error(request,"Must be Loggin in")
        return redirect('logreg:index')
    else:
        return redirect(reverse('Book:index'))

def logout(request):
    request.session.clear()
    return redirect('logreg:index')

side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/templates/Book/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>show result</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Book/css/index.css' %}">
  </head>
  </head>
  <body>
    <div id="wrapper">
      <a class="right_page" href="{% url 'Book:index' %}">Home Page</a>
      <a class="right_page" href="{% url 'logreg:logout' %}">Log Out</a>
      <div id="page">
        <h3>Add a new book title and review:</h3>
        <div id="main">
          {% if messages %}
            {% for message in messages %}
             <p>{{message}}</p>
            {% endfor %}
          {% endif %}
          <form class="" action="{% url 'Book:create_book' %}" method="POST">
            {% csrf_token %}
            <p>Title:<input type="text" name="title"></p>
            <p>Author:<ul>
              <li>Chose from the list:<select class="space"><option></option></select></li>
              <li>Or add a new author:<input class="space" type="text" name="author"></li>
            </ul></p>
            <p>Review:</p>
            <p><textarea cols="35" rows="5" placeholder="Add your Book Review Here" name="description"></textarea></p>
            <p>Rating:<select name="rating">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select></p>
            <input type="submit" value="Add Book and Review">
          </form >
        </div><!--close main-->
      </div><!--close page-->
    </div><!--close wrapper-->
  </body>
</html>

side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/templates/Book/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>This main page for belt review</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Book/css/index.css' %}">
  </head>
  <body>
   <div id="wrapper">
     <a class="right_page" href="{% url 'Book:add' %}">Add Book and Review</a>
     <a class="right_page" href="{% url 'logreg:logout' %}">Log Out</a>
     <div id="page">
       Welocme, {{request.session.user_first_name}}
       <div id="main">
         <div id="display_box1">
           <h3>Recent Book Reviews:</h3>
         </div>
         <div id="display_box2">
           <h3>Other Books with Views:</h3>
         </div>
       </div><!--close main-->
     </div><!--close page-->
   </div><!--close wrapper-->
  </body>
</html>

side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/templates/Book/result.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Book/css/index.css' %}">
  </head>
  <body>
     <div id="wrapper">
       <a class="right_page" href="{% url 'Book:add' %}">Add Book and Review</a>
       <a class="right_page" href="{% url 'logreg:logout' %}">Log Out</a>
       <div id="page">
         <h4>Welocme, {{request.session.user_first_name}}</h4>
        </div id="main">
        <h3>Review:</h3>
         <div id="display_box1">
           {% if Book %}
              {% for Book in Book %}
               <div class="reviews_box">
                <p>{{Book.Rating}}</p>
                <p>{{Book.review}}</p>
                <p>Post on {{Book.create_at}}</p>
               </div><!--close reviews_box-->
            {% endfor %}
           {% endif %}
           <a href="{% url 'Book:delet_review' %}">Delete the review</a>
         </div><!--close displaybox1-->
         <div id="display_box2">
             <h3>Add Review:</h3>
             <form class="" action="" method="">
               {% csrf_token %}
             <textarea cols="35" rows="5" placeholder="Add your Book Review Here"></textarea>
             <p>Rating:</p><input type="submit" value="submit review">
           </form>
         </div><!--close displaybox2-->
      </div><!--close main-->
    </div><!--close page-->
  </div><!--close wrapper-->
  </body>
</html>

side-project/DjangoEnv/Python_Fundamentals/review/apps/Book/templates/Book/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Show Result Html</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Book/css/index.css' %}">
  </head>
  </head>
  <body>
    <div id="wrapper">
      <a class="right_page" href="{% url 'Book:index' %}">Home</a>
      <a class="right_page" href="{% url 'Book:add' %}">Add Book and Review</a>
      <a class="right_page" href="{% url 'logreg:logout' %}">Log Out</a>
      <div id="page">
        <div id="main">
          <h3>User Alia:</h3>
        </div><!--close main-->
      </div><!--close page-->
    </div><!--close wrapper-->
  </body>
</html>