side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/appointment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name ='index'),
    url(r'^create_appointment$', views.create_appointment, name='create_appointment')
]

side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/logreg/urls.py
from django.conf.urls import url
from .models import User
from . import views
urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^register$',views.register, name="register"),
    url(r'^login$',views.login, name="login"),
    url(r'^main$',views.main, name="main"),
    url(r'^logout$',views.logout, name="logout")
]

side-project/DjangoEnv/Python_Fundamentals/second_belt/second_belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.logreg.urls', namespace='logreg')),
    url(r'^appointment/', include('apps.appointment.urls', namespace='appointment'))
]

side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/appointment/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from ..logreg.models import User

# Create your models here.
class AppointmentManager(models.Manager):
    def check_appointment(self,postdata):
        errors =[]
        response = {}

        if not len(postdata['task']):
            errors.append('Please fill out the task field ')
        if not len(postdata['date']):
            errors.append('Please fill out the date field ')

        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status'] = True
            self.create(task=postdata['task'],date=postdata['date'])
        return response



class Appointment(models.Model):
    task = models.CharField(max_length=255)
    date = models.DateField(auto_now=False, auto_now_add=False)
    user = models.OneToOneField(User)
    create_at = models.DateTimeField(auto_now_add= True)
    update_at = models.DateTimeField(auto_now = True)
    objects = AppointmentManager()

side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/logreg/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-z0-9.+_-]+@[a-zA-z0-9._-]+\.[a-zA-z]+$')
# Create your models here.
class UserManager(models.Manager):
    def add_user(self, postData):
        print postData

        errors = []

        if not postData['first_name']:
            errors.append('First name field is required')
        if len(postData['first_name']) < 2:
            errors.append('First name must be at least 2 characters long.')
        if not postData['last_name']:
            errors.append('Last name field is required')
        if len(postData['last_name']) < 2:
            errors.append('Last name must be at least 2 characters long.')
        if not postData['email']:
            errors.append('Email field is required')
        if not EMAIL_REGEX.match(postData['email']):
            errors.append('Enter a valid email')
        if not postData['password']:
            errors.append('Password is required')
        if not postData['password'] == postData['confirm_password']:
            errors.append('Password must match')
        if not postData['date_of_birth']:
            errors.append('Enter Your date of birth')

        user = self.filter(email=postData['email'])
        if user:
            errors.append('Email already exists')

        response = {}

        if errors:
            response['status'] = False
            response['errors'] = errors

        else:
            password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            new_user = self.create(first_name = postData['first_name'],
                        last_name = postData['last_name'],
                        email = postData['email'],
                        password = password,
                        date_of_birth = postData['date_of_birth']
            )
            response['status'] = True
            response['new_user'] = new_user

        return response

    def check_user(self, postData):
        user = self.filter(email=postData['email'])
        errors = []
        response = {}
        if user:
           #validate User login information
           #bcrypt.checkpw(postData['password'].encode(), bcrypt.gensalt())
           if bcrypt.hashpw(postData['password'].encode(), user[0].password.encode()) == user[0].password.encode():
               print("It Matched")
               response['status'] = True
               response['login_user'] = user[0]
           else:
               print("It Does Not Match")
               errors.append('Invalide email/password combinnation')
               response['status'] = False
               response['errors'] = errors
        else:
           #email does not exists in database
           errors.append('Email does not exist.')
           response['status'] = False
           response['errors'] = errors

        return response


class User(models.Model):
     first_name = models.CharField(max_length=55)
     last_name = models.CharField(max_length=55)
     email = models.EmailField()
     password = models.CharField(max_length=55)
     confirm_password = models.CharField(max_length=55)
     date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
     objects = UserManager()

side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/appointment/views.py
from django.shortcuts import render, redirect
from ..logreg.models import User
from .models import Appointment
from django.contrib import messages

# Create your views here.
def index(request):
    context = {
         "Appointment":Appointment.objects.all(),
    }
    return render(request,'appointment/index.html',context)


def create_appointment(request):
    response = Appointment.objects.check_appointment(request.POST)
    if not response['status']:
        for error in response['errors']:
            messages.error(request, error)
    return redirect('index')

side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/logreg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.core.urlresolvers import reverse
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, 'logreg/index.html')

def register(request):
    response = User.objects.add_user(request.POST)
    if response['status']:
        # successful add a new user in here
       request.session['user_id'] = response['new_user'].id
       request.session['user_first_name'] = response['new_user'].first_name
       request.session['user_last_name'] = response['new_user'].last_name
       return redirect('logreg:main')
    else:
       for error in response['errors']:
           messages.error(request, error)
    return redirect('logreg:index')

def login(request):
    response = User.objects.check_user(request.POST)
    if response['status']:
        # successful login user in here
       request.session['user_id'] = response['login_user'].id
       request.session['user_first_name'] = response['login_user'].first_name
       request.session['user_last_name'] = response['login_user'].last_name
       return redirect('logreg:main')
    else:
       #falid to validate
       for error in response['errors']:
           messages.error(request, error)
       return redirect('logreg:index')

def main(request):
    if "user_id" not in request.session:
        messages.error(request,"Must be Loggin in")
        return redirect('logreg:index')
    else:
        return redirect(reverse('appointment:index'))

def logout(request):
    request.session.clear()
    return redirect('logreg:index')

side-project/DjangoEnv/Python_Fundamentals/second_belt/apps/appointment/templates/appointment/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Second Belt Exam</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'appointment/css/index.css' %}">
    <script>
function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('txt').innerHTML = "Time for now is:"+ h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
}
function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
</script>
  </head>
  <body onload="startTime()">
    <div id="wrapper">
      <div id="page">
        <h3>Hello, {{request.session.user_first_name}}</h3>
        <div id="main">
         <h4 id="txt"></h4>
        <h4>Your Other Appointments:</h4>
        <table>
          <tr>
            <td>Task</td>
            <td>Time</td>
            <td>status</td>
            <td>Action</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </table>

        <h4>Your Other Appointments:</h4>
        <table>
          <tr>
            <td>Task</td>
            <td>Date</td>
            <td>Time</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </table>

        <h4>Add Appointment:</4>
          {% if messages %}
            {% for message in messages %}
             <p>{{message}}</p>
            {% endfor %}
           {% endif %}
          <form class="" action="{% url 'appointment:create_appointment' %}" method="POST">
            {% csrf_token %}
            <ul>
              <li><label class="" for="date">Date:</label>
              <input class="" type="date" name="date"></li>
              <li><label class="" for="task">Task:</label>
              <input class="" type="text" name="task"></li>
              <input id="shift" type="submit" value="Add Appointment">
            </ul>
          </form>
       </div><!--close main-->
      </div><!--close page-->
    </div><!--close wrapper-->
  </body>
</html>